force-app/main/default/objects/Opportunity/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <description>Customer&apos;s billing address information</description>
    <label>Billing Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Clients email</description>
    <label>Email</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description
  >Use this field to add specfic event requests for new EME Distributor or Supplier Leads</description>
    <label>Event Name</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName
        >EME Exclusive #1 February 25-28, 2024, Embassy Suites Deerfield Beach Resort &amp; Spa, Deerfield Beach, FL</fullName>
                <label
        >EME Exclusive #1 February 25-28, 2024, Embassy Suites Deerfield Beach Resort &amp; Spa, Deerfield Beach, FL</label>
            </value>
            <value>
                <fullName
        >EME Exclusive #2 May 5-8, 2024, Embassy Suites by Hilton St Augustine Beach Oceanfront Resort, St. Augustine, FL</fullName>
                <label
        >EME Exclusive #2 May 5-8, 2024, Embassy Suites by Hilton St Augustine Beach Oceanfront Resort, St. Augustine, FL</label>
            </value>
            <value>
                <fullName
        >EME Team Solutions June 23-25, 2024, Embassy Suites by Hilton Boulder, Boulder, CO</fullName>
                <label
        >EME Team Solutions June 23-25, 2024, Embassy Suites by Hilton Boulder, Boulder, CO</label>
            </value>
            <value>
                <fullName
        >EME Exclusive #3 August 4-7, 2024, Westgate Park City Resort &amp; Spa, Park City, UT</fullName>
                <label
        >EME Exclusive #3 August 4-7, 2024, Westgate Park City Resort &amp; Spa, Park City, UT</label>
            </value>
            <value>
                <fullName
        >EME Exclusive #4 September 15-18, 2024, Zachari Dunes on Mandalay Beach, Curio Collection by Hilton, Oxnard, CA</fullName>
                <label
        >EME Exclusive #4 September 15-18, 2024, Zachari Dunes on Mandalay Beach, Curio Collection by Hilton, Oxnard, CA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Industry_Number__c.field-meta.xml
<CustomField>
    <fullName>Industry_Number__c</fullName>
    <description
  >This is an industry identiying number (ASI, PPAI, SAGE, or Other)</description>
    <externalId>true</externalId>
    <inlineHelpText
  >This is an industry identiying number (ASI, PPAI, SAGE, or Other)</inlineHelpText>
    <label>Industry Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/WordPressContactUsForm_Test.cls
@isTest
public class WordPressContactUsForm_Test {
  @testSetup
  static void generateTestAccounts() {
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    Account acc = new Account(
      Name = 'Phun For All',
      Billing_Email__c = 'Test@Test.com',
      Art_Approval_Email__c = 'Test@Test.com',
      QuickBooks_Accounts__c = 'Team Phun',
      BillingStreet = '123 Test Street',
      BillingCity = 'Test City',
      BillingState = 'Test State',
      BillingPostalCode = '12345',
      BillingCountry = 'Test Country',
      RecordTypeId = '0128M0000000FbgQAE'
    );
    insert acc;

    Contact con = new Contact(
      FirstName = 'Test',
      LastName = 'Last',
      AccountId = acc.id,
      Email = 'Test@Test.com'
    );
    insert con;

    Contact con2 = new Contact(
      FirstName = 'Testing',
      LastName = 'Last',
      AccountId = acc.id,
      Email = 'Testad@Test.com'
    );
    insert con2;

    Opportunity newOpportunity = new Opportunity();
    newOpportunity.Name = 'firstName' + ' ' + 'lastName' + ' Opportunity';
    newOpportunity.Email__c = 'Test@Test.com';
    newOpportunity.Phone__c = '654651651';
    newOpportunity.Company__c = 'company';
    newOpportunity.Title__c = 'title';
    newOpportunity.Industry_Number__c = 'ASI';
    newOpportunity.Billing_Address__c = 'address';
    //  newOpportunity.Event_Name__c = String.join(Events, ';');
    newOpportunity.AccountId = acc.Id;
    newOpportunity.Contact__c = con.Id;
    newOpportunity.StageName = 'Needs Analysis';
    newOpportunity.CloseDate = System.today() + 7;
    insert newOpportunity;
  }

  @isTest
  static void test1() {
    Test.startTest();
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();

    req.requestURI = '/services/apexrest/ContactUs'; //Request URL
    req.httpMethod = 'POST';
    req.addHeader('Content-Type', 'application/json');
    req.requestBody = Blob.valueOf(
      '{  "firstName": "John",  "lastName": "Doe",  "email": "john.doe@example.com",  "company": "ABC Corp",  "venues": "Event Venue XYZ",  "phone": "123-456-7890",  "message": "I am interested in your services.",  "flag": "About Us",  "howDidYouHear": "Social Media",  "interestedIn": ["Brand Ambassador", "In Store Demos"]}'
    );

    RestContext.request = req;
    RestContext.response = res;
    WordPressContactUsForm.doPost();
    ////////////////
    RestRequest req2 = new RestRequest();
    RestResponse res2 = new RestResponse();

    req2.requestURI = '/services/apexrest/ContactUs'; //Request URL
    req2.httpMethod = 'POST';
    req2.addHeader('Content-Type', 'application/json');
    req2.requestBody = Blob.valueOf(
      '{  "firstName": "Johnny",  "lastName": "Doe",  "email": "john.doe@example.com",  "company": "ABC Corp",   "venues": "Event Venue XYZ",  "phone": "123-456-7890",  "message": "I am interested in your services.",  "flag": "About Us",  "howDidYouHear": "Social Media",  "interestedIn": ["Brand Ambassador", "In Store Demos"]}'
    );

    RestContext.request = req2;
    RestContext.response = res2;
    WordPressContactUsForm.doPost();

    Test.stopTest();
  }

  @isTest
  static void test2() {
    Test.startTest();
    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();

    req.requestURI = '/services/apexrest/ContactUs'; //Request URL
    req.httpMethod = 'POST';
    req.addHeader('Content-Type', 'application/json');
    req.requestBody = Blob.valueOf(
      '{  "firstName": "John",  "lastName": "Doe",  "email": "john.doe@example.com",  "company": "ABC Corp",   "venues": "Event Venue XYZ",  "phone": "123-456-7890",  "message": "I am interested in your services.",  "flag": "About Us",  "howDidYouHear": "Social Media",  "interestedIn": ["Brand Ambassador", "In Store Demos"]}'
    );

    RestContext.request = req;
    RestContext.response = res;
    WordPressContactUsForm.doPost();
    ////////////
    RestRequest req2 = new RestRequest();
    RestResponse res2 = new RestResponse();

    req2.requestURI = '/services/apexrest/ContactUs'; //Request URL
    req2.httpMethod = 'POST';
    req2.addHeader('Content-Type', 'application/json');
    req2.requestBody = Blob.valueOf(
      '{  "firstName": "Johnny",  "lastName": "Doe",  "email": "john.doe@example.com",  "company": "ABC Corp",  "venues": "Event Venue XYZ",  "phone": "123-456-7890",  "message": "I am interested in your services.",  "flag": "About Us",  "howDidYouHear": "Social Media",  "interestedIn": ["Brand Ambassador", "In Store Demos"]}'
    );

    RestContext.request = req2;
    RestContext.response = res2;
    WordPressContactUsForm.doPost();

    Test.stopTest();
  }
}